
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:49153/loja
    password: mariadbpw
  jpa:
    hibernate:
      ddl-auto: update
